spring.application.name=coldtrace-api-gateway
server.port=${PORT:8080}
coldtrace.monitoring.url=${MONITORING_URL:http://localhost:8083}
coldtrace.backend.url=${BACKEND_URL:http://localhost:8090}
coldtrace.alert.url=${ALERT_URL:http://localhost:8084}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
spring.cloud.gateway.httpclient.connect-timeout=3000
spring.cloud.gateway.httpclient.response-timeout=5s

coldtrace.report.url=${REPORT_URL:http://localhost:8085}

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=${WEB_ORIGINS:http://127.0.0.1:4200,http://localhost:4200}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=Authorization,Content-Type,X-Correlation-Id,Last-Event-ID
spring.cloud.gateway.globalcors.cors-configurations.[/**].exposed-headers=X-Correlation-Id
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
